# Generated by Django 2.2.7 on 2020-06-20 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('grado', models.CharField(max_length=10)),
                ('nivel', models.CharField(max_length=50)),
            ],
        ),
    ]
