# Generated by Django 2.2.7 on 2020-06-20 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('educa', '0002_alumno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_periodo', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='aula',
            options={'ordering': ['id'], 'verbose_name': 'aula', 'verbose_name_plural': 'aulas'},
        ),
        migrations.AlterModelTable(
            name='aula',
            table='educa_aula',
        ),
        migrations.CreateModel(
            name='Aula_Periodo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educa.Aula')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educa.Periodo')),
            ],
        ),
    ]
