# Generated by Django 3.0.7 on 2020-06-21 01:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('educa', '0003_auto_20200620_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Aula_Curso_Docente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educa.Aula')),
            ],
            options={
                'verbose_name': 'Aula_Curso_Docente',
                'verbose_name_plural': 'Aulas_Cursos_Docentes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_curso', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['nombre_curso'],
            },
        ),
        migrations.CreateModel(
            name='Curso_docente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educa.Curso')),
            ],
            options={
                'verbose_name': 'Curso_Docente',
                'verbose_name_plural': 'Cursos_Docentes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Notas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nota', models.IntegerField()),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_aula_periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educa.Aula_Periodo')),
                ('id_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educa.Curso')),
            ],
        ),
        migrations.DeleteModel(
            name='Alumno',
        ),
        migrations.AddField(
            model_name='aula_curso_docente',
            name='curso_docente_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educa.Curso_docente'),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='id_curso_docente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educa.Curso_docente'),
        ),
    ]
