# Generated by Django 2.2.7 on 2020-06-20 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('educa', '0003_auto_20200620_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_curso', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['nombre_curso'],
            },
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=200)),
                ('Apellidos', models.CharField(max_length=200)),
                ('Edad', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Docente',
                'verbose_name_plural': 'Docentes',
                'ordering': ['Nombre'],
            },
        ),
        migrations.CreateModel(
            name='Notas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nota', models.IntegerField()),
                ('id_alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educa.Alumno')),
                ('id_aula_periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educa.Aula_Periodo')),
                ('id_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educa.Curso')),
            ],
        ),
        migrations.CreateModel(
            name='Curso_docente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educa.Curso')),
                ('id_docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educa.Docente')),
            ],
            options={
                'verbose_name': 'Curso_Docente',
                'verbose_name_plural': 'Cursos_Docentes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Aula_Curso_Docente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educa.Aula')),
                ('curso_docente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educa.Curso_docente')),
            ],
            options={
                'verbose_name': 'Aula_Curso_Docente',
                'verbose_name_plural': 'Aulas_Cursos_Docentes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('id_alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educa.Alumno')),
                ('id_curso_docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educa.Curso_docente')),
            ],
        ),
    ]
